# Generated by Django 2.0.4 on 2018-05-13 08:47

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=uuid.UUID('5fce6c0f-72f3-4421-a068-17bafa8e9175'), max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 13, 8, 47, 36, 138276)),
        ),
    ]
