# Generated by Django 2.0.4 on 2018-05-13 13:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180513_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 13, 13, 25, 26, 722339, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=uuid.UUID('33ec9886-cc0d-47b3-817e-0faa86e14ec0'), max_length=50),
        ),
    ]
