# Generated by Django 2.0.4 on 2018-05-16 09:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20180516_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 16, 9, 43, 45, 16440, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=uuid.UUID('a833fbff-7fd6-422c-a7e9-4d6d55b8cba7'), max_length=50),
        ),
    ]
