# Generated by Django 2.0.4 on 2018-05-16 09:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20180516_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='comment',
            field=models.CharField(default='has no some comment.', max_length=50),
        ),
        migrations.AlterField(
            model_name='status',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 16, 9, 43, 45, 17242, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_id',
            field=models.CharField(default=uuid.UUID('33e51d82-e44f-4190-bb30-76a4e8878b4c'), max_length=50),
        ),
    ]
